### ISSUE TITLE
TEXTFUSENET_MUTIL_PATH_FUSE_ON

### ISSUE THREAD

**Issue by hossein-moghaddam** [ying09/TextFuseNet.pytorch#69]
Hi.
Could anyone tell me what is this "TEXTFUSENET_MUTIL_PATH_FUSE_ON" in the configs doing? because when this is enabled I get this error: ` The size of tensor a (2) must match the size of tensor b (36) at non-singleton dimension 0`
 but when I disable this the error is gone. but I'm afraid this could affect the performance. thank you so much.

**Comment by Real-YeJ** [comment]
@h311-git "TEXTFUSENET_MUTIL_PATH_FUSE_ON" means using the multi_path_features_fusion module.

**Comment by hossein-moghaddam** [comment]
> @h311-git "TEXTFUSENET_MUTIL_PATH_FUSE_ON" means using the multi_path_features_fusion module.

Thank you so much for your response. but do you have any idea why am i getting this error when this is enabled?

**Comment by hossein-moghaddam** [comment]
I found the solution :). the problem was because I had changed the batch size. anyway, thank you.
