### ISSUE TITLE
Could someone kindly explain "For calculating F-measure, Recall, and Precision, please refer to the following links:".

### ISSUE THREAD

**Issue by allenmatt98** [ying09/TextFuseNet.pytorch#71]
I couldn't find any scripts I could use to calculate the f-measure, precision and recall in the icdar 2015 link mentioned. Could someone please elaborate ? I'd be extremely grateful

**Comment by Real-YeJ** [comment]
@allenmatt98 hey, you need register in the ICDAR web and then submit your result.
![image](https://user-images.githubusercontent.com/37889627/130377337-537d4296-78f0-4cd5-af88-a761c38640f8.png)

**Comment by allenmatt98** [comment]
> @allenmatt98 hey, you need register in the ICDAR web and then submit your result.
> ![image](https://user-images.githubusercontent.com/37889627/130377337-537d4296-78f0-4cd5-af88-a761c38640f8.png)

Thanks a lot !! Much appreciated :)

**Comment by ivand9** [comment]
@allenmatt98 @Real-YeJ  which file i need to upload on ICDAR web?
