### ISSUE TITLE
关于数据集转COCO和网络代码的问题

### ISSUE THREAD

**Issue by lifuguan** [ying09/TextFuseNet.pytorch#81]
你好，首先感谢大佬的工作，目前我正在学习detectron2和检测，关于该项目有两个问题想请教：

1. 数据集的COCO格式转换
目前我看了一圈，没有看到代码里有关于ICDAR2015的custom dataset的代码。请问是怎么实现的呢？

2. 关于该网络代码的疑问
看了一圈，没有找到任何和TextFuseNet有关的类，请问是将代码写在detectron2的库里面了吗？

**Comment by Real-YeJ** [comment]
@lifuguan 
1. custom dataset的标注转换为detectron2训练用的json文件，只需要根据COCO数据集的格式 用python自己写个脚本就行了
2. TextFuseNet具体代码在seg_head 和 multi_path_fuse_module。也可以直接把自己的模块写在projects里，具体请参考detectron2 codebase.
