### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by sssimpleboy** [ying09/TextFuseNet.pytorch#93]
感谢大佬的付出
比如我有一个box是检测到的单词“sort”，又会有一个box含有"sort"中的“o”，并且当做两个目标！

**Comment by sssimpleboy** [comment]
ctw1500 的模型好像只检测 “text”  类？ 但是我用它训练时，又说 类别不相等 ["text","0".....,"z"] !=["text"].

**Comment by sssimpleboy** [comment]
根据论文，团队说只保留了单词实例的实例分割结果作为最终的文本检测结果。 
我在使用ICDAR2013训练出的模型进行测试时，得到的结果还有别的类，比如1,2,3,4,5,6,7,8,9,a,b,c等。
我在使用CTW1500训练出的模型测试时，得到的结果只有0 ，"text"类，符合论文描述情况。
想知道这是怎么回事。
另外在使用ICDAR2013的模型时，检测出的一些text类别中间还有字符级的类别，即两种有重合，这能算是误检吗？
我还想知道这两个数据集在训练时提供的json和最后的模型有何不同?   
代码文件提供的样例是有 63例的，但我不确定是否两个数据集的json都是这样，或者说ctw的在最后输出部分改了代码？
但根据检测结果，CTW还可以检测到中文，别的数据集都不可以。
因为我想用自己的训练集生成一个像CTW那样的模型，所以问题比较多。
谢谢。

**Comment by ying09** [comment]
因为CTW数据集的效果在当时已经取得SOTA性能，所以我们当时就没有再用生成字符伪标签的方式去训练。
