### ISSUE TITLE
Is it possible to run demo on torch>=1.6.0?

### ISSUE THREAD

**Issue by dangcaptkd2** [ying09/TextFuseNet.pytorch#97]
Hi, I want to run demo on torch==1.6.0 but get: `RuntimeError: Error compiling objects for extension
` when I run `python setup.py build develop`. Is there anyway to run demo on torch>=1.6.0?

Thanks in advance

**Comment by ying09** [comment]
Sorry, the student done this work have graduated, so we don't have the energy to adapt to the Torch version you mentioned.
