### ISSUE TITLE
关于生成字符伪标签mask的问题

### ISSUE THREAD

**Issue by LIYHUI** [ying09/TextFuseNet.pytorch#99]
@ying09 您好，感谢您的工作！我使用synthtext_pretrain model 在icdar2015上生成伪标签时，发现部分字符预测结果的异常：有些字符可以得到pred box, 但是pred mask 全为0。对于这种字符 mask预测效果不好，但是字符box预测很好的，您会怎么处理？

**Comment by ying09** [comment]
是的。ICDAR 2015数据集因为字符目标普遍很小，所以生成伪标签的时候会存在很多字符box检测很好，但是mask不理想的情况，像这种情况，我们将box置信度大于0.7的case，通过fill box的方式生成mask。（因为这个工作有点久远，具体阈值是0.7还是0.8有点记不太清楚)。

**Comment by LIYHUI** [comment]
ok, thanks
